apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webappdeploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  