apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webappdeploy
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 5
    scaleDown:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30
  # targetCPUUtilizationPercentage: 50
  