apiVersion: apps/v1
kind: Deployment
metadata:
  name: websampledeploy
  labels:
    app: websample-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: demowebsample
        imagePullPolicy: Always
        image: "rtejac/web_app:v1.0"
        command: ["python3"]
        args: ["web_app.py"]
        ports:
          - containerPort: 8881





































# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mosquitto
#   labels:
#     app: mosquitto
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mosquitto
#   template:
#     metadata:
#       labels:
#         app: mosquitto
#     spec:
#       containers:
#         - name: mosquitto
#           image: eclipse-mosquitto:1.6.2
#           ports:
#             - containerPort: 1883