# Default values for myhelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  name: docker.io/rtejac/web_app
  pullPolicy: Always
  restartPolicy: Never
  tag: "v1.0"

dep:
  name: webappsdeploy
  appName: websample-app

pod:
  name: webapppod
  appName: mywebapp

containerPort: 8881

service:
  name: webappservice
  port: 8881
  targetPort: 8881
  type: NodePort #ClusterIP #
  nodePort: 30008




ingName: myingress
