apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapprs
  labels:
    app: webapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: webapppod
        imagePullPolicy: Always
        image: "rtejac/web_app:v1.0"
        command: ["python3"]
        args: ["web_app.py"]
        ports:
          - containerPort: 8881